### ISSUE TITLE
Saving to NetCDF converts RangeAxis of Ints to RangeAxis of Floats

### ISSUE THREAD

**Issue by felixcremer** [meggart/YAXArrays.jl#33]
I am trying to write some unit tests for CubeIO and I found that NetCDF converts the Axis of Ints to an Axis of Floats. 
This is on random data with three dimensions and I get these axes types:
```julia
julia> nccube.axes
3-element Array{RangeAxis{Float64,S,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}} where S,1}:
 Dim_1               Axis with 10 Elements from 1.0 to 10.0
 Dim_2               Axis with 20 Elements from 1.0 to 20.0
 Dim_3               Axis with 30 Elements from 1.0 to 30.0

julia> yax.axes
3-element Array{RangeAxis{Int64,_A,Base.OneTo{Int64}} where _A,1}:
 Dim_1               Axis with 10 Elements from 1 to 10
 Dim_2               Axis with 20 Elements from 1 to 20
 Dim_3               Axis with 30 Elements from 1 to 30
```
yax is the random data loaded as YAXArray and nccube is after doing a 
`savecube(yax, outpath, backend=:netcdf)`.

I am not sure, whether this is really an issue, but it was at least unexpected for me.

**Comment by meggart** [comment]
The problem is in this function: https://github.com/meggart/YAXArrays.jl/blob/a8f5e77de3182ab244771449e2406da3114d455d/src/DatasetAPI/Datasets.jl#L131 

which converts a dense array to a range if this is appropriate to allow faster lookup later. There should be another method specialized on integer-type arrays which uses a StepRange instead to maintain the element type.
