### ISSUE TITLE
YAXArrays.Cube throws BoundsError

### ISSUE THREAD

**Issue by alex-s-gardner** [meggart/YAXArrays.jl#92]
First of all, thank you for sharing your code... it should be really helpful. I'm having an issue with using YAXArrays.Cube on a Zarr dataset. I can open the file using Zarr.jl but I get an indexing error when using YAXArrays.Cube()

Here's my MWE
#  ------------------------------------
Pkg.add("YAXArrays")

#path to zarr file created with xarray
path = "http://its-live-data.s3.amazonaws.com/datacubes/v02/N60W040/ITS_LIVE_vel_EPSG3413_G0120_X-150000_Y-2250000.zarr";

YAXArrays.Cube(path)

#  ------------------------------------

throws the error:
LoadError: BoundsError: attempt to access 0-element Vector{Any} at index [1]

Any feedback would be greatly appreciated

**Comment by felixcremer** [comment]
You can't open this file as a datacube, because it is a bundle of multiple datasets which have different dimensions. 
You can use `ds = open_dataset(path)`  to open it as an YAXArray.Dataset, which is basically a collection of multiple datacubes. 
With `ds.cubes` you can see the collection of these datacubes. 

We should provide a better error message for trying to open such a file,  so that it would be clear, what is happening. 

Feel free to ask additional questions, or open issues, when something is unclear or not working.

**Comment by alex-s-gardner** [comment]
@felixcremer thanks a ton!  

ds = YAXArrays.open_dataset(path[1])
a = ds.v.data;

works like a charm
